### ISSUE TITLE
Popup shown at Display-Bottom

### ISSUE THREAD

**Issue by maruhe** [PetrVobornik/ColorPicker#10]
hi there and thanks a lot! great work!
just the ColorPickerDialog opens at the bottom of the screen and I have to sroll inside the Dialog to set the Color :-(
happen on windows, android and also in Xam.Plugin.SimpleColorPicker
I didn't found the definition of size and position :-(
regards

**Comment by PetrVobornik** [comment]
Hello,
you can change a width of some components in dialog by [ColorDialogSettings](https://github.com/PetrVobornik/ColorPicker/blob/master/src/ColorPickerDialog.cs#L88). Total width is calculated as a sum of these partial widths. A height is calculated by the same principle but in this case each component has only the standard height. But all content is in [ScrollViewer](https://github.com/PetrVobornik/ColorPicker/blob/master/src/ColorPickerDialog.cs#L195) now.
Could you please send me screenshoot with this error, version numbers of used components (ColorPicker, XamarinForms, OS) and part of your source code? 
Thank you
