### ISSUE TITLE
getting the hex value?

### ISSUE THREAD

**Issue by jagunosra** [PetrVobornik/ColorPicker#13]
Hi,

I just want to ask how to get the hex value from the textbox?

**Comment by AlexHedley** [comment]
Depending on what your property is called:
`<cp:ColorPickerEntry WidthRequest="150" HorizontalOptions="Start" Color="{Binding EditedColor}" />`

Or
`public Color EditedColor ...`

You can then convert it, pass in `EditedColor`:
https://www.c-sharpcorner.com/article/hex-colors-in-C-Sharp/

*ColorToHex*
```
 public static String ColorToHex(Color actColor)
// Translates a .NET Framework Color into a string containing the html hexadecimal 
// representation of a color. The string has a leading '#' character that is followed 
// by 6 hexadecimal digits.
{
return "#"+IntToHex(actColor.R,2)+IntToHex(actColor.G,2)+IntToHex(actColor.B,2);
} 
```

**Comment by AlexHedley** [comment]
[ColorPickerUtils.cs](https://github.com/PetrVobornik/ColorPicker/blob/master/src/ColorPickerUtils.cs) has a helper function: [ToHex](https://github.com/PetrVobornik/ColorPicker/blob/master/src/ColorPickerUtils.cs#L13)
