### ISSUE TITLE
Improve UI of colorpicker

### ISSUE THREAD

**Issue by galadril** [PetrVobornik/ColorPicker#3]
Maybe you could rework this colorpicker to look better like: 

![image](https://user-images.githubusercontent.com/14561640/45001748-15e22280-afd0-11e8-9cbc-319634ad2aa2.png)

to make the dialog less techy

![image](https://user-images.githubusercontent.com/14561640/45001757-34481e00-afd0-11e8-836e-ae8551034f01.png)

For example if you color the progressbars you dont need the text values at the left

**Comment by PetrVobornik** [comment]
Thank you, I implemented some changes from you branch, but GUI was not changed. Thank you for your ideas and whole branch, it is good alternative for this component, if anybody prefer your design.
