### ISSUE TITLE
Library Incompatible with Android Support Libraries (v27.0.2.1)

### ISSUE THREAD

**Issue by Axemasta** [PetrVobornik/ColorPicker#8]
You cannot install and use this package when android is using the v27.0.2.1 support libraries.

**Comment by PetrVobornik** [comment]
Yes, NuGet 1.0.23 was compilled with Xamarin.Forms 3.6.0.293080 which uses Android components from version 28.0.0.1. But you can download the source code from GitHub and recompile it with older Xamarin version, it should be compatible.
